### ISSUE TITLE
Installing on Ubuntu

### ISSUE THREAD

**Issue by gazzenger** [Robpol86/UnofficialDDNSnix#3]
Hi,  I'm trying to install the program on Ubuntu, I run build_deb.sh but I'm not sure what I'm meant to do next. 

Kind Regards, 
Gary

**Comment by Robpol86** [comment]
This should work instead, you won't need build_deb.sh:

1. Download https://github.com/Robpol86/UnofficialDDNSnix/releases/download/v1.0.0/unofficialddns_1.0.0_all.deb
2. Run `sudo dpkg -i unofficialddns_1.0.0_all.deb`
