### ISSUE TITLE
Issue with API Token

### ISSUE THREAD

**Issue by gazzenger** [Robpol86/UnofficialDDNSnix#4]
Hi,

I noticed last month my ubuntu webserver stopped updating my ip address to the name.com DNS records.

I looked into the log file, and it is says my API token was incorrect, but I know it was working fine for a long time, so I assumed it was something to do with the domain registrar name.com.

I emailed them asking about my API token, and they replied with a new API token, however this new token is a lot larger.

My old token length was 40 characters long, and my new token length is 139 characters.
Even weirder is the test API URL token is 135 characters long.

Any help would be great,

Cheers
Gary

**Comment by waterfoul** [comment]
I've fixed it in my repo, it looks like name.com removed a restriction on the characters which can be in the session token. I created a PR to fix this repo but for now you can check out https://github.com/waterfoul/UnofficialDDNSnix

**Comment by Robpol86** [comment]
I'm not sure when I'll make a release. I've got a few things I need to do this and next week. Perhaps the week after if I get some time.
